//
//  ReportsView.swift
//  NEW5
//
//  Generate and share medical reports. Data stored securely in Application Support.
//

import SwiftUI
import SwiftData

struct ReportsView: View {
    @Environment(\.modelContext) private var modelContext
    @State private var startDate = Calendar.current.date(byAdding: .day, value: -30, to: Date()) ?? Date()
    @State private var endDate = Date()
    @State private var reportURL: URL?
    @State private var errorMessage: String?
    @State private var isGenerating = false

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                Text("Medical reports")
                    .font(.title2.weight(.semibold))
                    .foregroundStyle(Color(red: 0.12, green: 0.3, blue: 0.2))

                Text("Generate a PDF report of your health data (glucose, meals, sugar, medications) for the selected period. Reports are stored securely on device.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                VStack(alignment: .leading, spacing: 12) {
                    DatePicker("From", selection: $startDate, displayedComponents: .date)
                    DatePicker("To", selection: $endDate, displayedComponents: .date)
                }
                .padding(16)
                .background(Color.white)
                .clipShape(RoundedRectangle(cornerRadius: 14))
                .shadow(color: .black.opacity(0.04), radius: 8, x: 0, y: 2)

                if let err = errorMessage {
                    Text(err)
                        .font(.subheadline)
                        .foregroundStyle(.red)
                        .padding(12)
                        .background(Color.red.opacity(0.1))
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                }

                Button {
                    generateReport()
                } label: {
                    HStack {
                        if isGenerating {
                            ProgressView()
                                .tint(.white)
                        } else {
                            Label("Generate report", systemImage: "doc.badge.plus")
                        }
                    }
                    .font(.headline)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 16)
                    .background(Color(red: 0.2, green: 0.55, blue: 0.35))
                    .foregroundStyle(.white)
                    .clipShape(RoundedRectangle(cornerRadius: 14))
                }
                .disabled(isGenerating || startDate > endDate)

                if let url = reportURL {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Report ready")
                            .font(.headline)
                            .foregroundStyle(Color(red: 0.12, green: 0.3, blue: 0.2))
                        ShareLink(item: url, subject: Text("SugarScope health report"), message: Text("Health report generated by SugarScope")) {
                            Label("Share report", systemImage: "square.and.arrow.up")
                                .font(.headline)
                                .frame(maxWidth: .infinity)
                                .padding(.vertical, 14)
                                .background(Color(red: 0.25, green: 0.5, blue: 0.4))
                                .foregroundStyle(.white)
                                .clipShape(RoundedRectangle(cornerRadius: 12))
                        }
                    }
                }
            }
            .padding(20)
        }
        .background(Color(red: 0.96, green: 0.98, blue: 0.96))
        .navigationTitle("Reports")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func generateReport() {
        errorMessage = nil
        reportURL = nil
        isGenerating = true
        let start = startDate
        let end = endDate
        Task { @MainActor in
            do {
                let url = try MedicalReportGenerator.generate(from: start, to: end, modelContext: modelContext)
                reportURL = url
            } catch {
                errorMessage = "Could not generate report: \(error.localizedDescription)"
            }
            isGenerating = false
        }
    }
}

#Preview {
    NavigationStack {
        ReportsView()
    }
    .modelContainer(for: [HealthLogEntry.self, Medication.self, ReminderConfig.self], inMemory: true)
}
